### ISSUE TITLE
Confusing user routes

### ISSUE THREAD

**Issue by mselee** [seleem1337/Slyde#12]
There are many confusing/old urls for the user process, please refactor them and remove unneeded routes.
@mo2men1 @mohamed-mamdouh95

**Comment by mo2men1** [comment]
b2a ana te2olly confusing??? -_-

**Comment by mselee** [comment]
Da msh confusing ? :'D

```
get 'login' => "sessions#new", as: "login"
delete 'logut' => "sessions#destroy", as: "logut"

post 'users/loginValidate'

get 'users/login'
post 'users/loginValidate'

get 'users/new'
post 'users/create'
```

**Comment by mo2men1** [comment]
:"D la2 wad7a el 3'alta yan3y msh confusing wala 7aga :unamused:

**Comment by mselee** [comment]
hsebk le damerk :'D
